base_model: allenai/OLMo-2-0425-1B
seed: 1

# Automatically upload checkpoint and final model to HF
hub_model_id: andrwu/OLMo-2-1B-SFT-axolotl

deepspeed: configs/olmo2-sft-ds.json

datasets:
  - path: allenai/tulu-3-sft-olmo-2-mixture-0225
    type: chat_template
    chat_template: jinja
    chat_template_jinja: configs/olmo2-chat-template.jinja 
    roles_to_train: ["assistant"]
    train_on_eos: turn

val_set_size: 0.0
output_dir: ./outputs/OLMo-2-1B-SFT

sequence_len: 4096
sample_packing: false
excess_length_strategy: 'truncate'

wandb_project: axolotl-test
wandb_entity: zettafleet
wandb_name: olmo-2-1b-sft

gradient_accumulation_steps: 8
micro_batch_size: 2
num_epochs: 2
optimizer: adamw_torch_fused
lr_scheduler: linear
learning_rate: 3e-5

bf16: true
tf32: false

gradient_checkpointing: true
logging_steps: 1
flash_attention: true

warmup_ratio: 0.03
evals_per_epoch: no
saves_per_epoch: 4
